"""Add community_follower table

Revision ID: 0f0d68a4df3b
Revises: 2ff2c8b0a045
Create Date: 2025-12-11 12:28:42.511114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f0d68a4df3b'
down_revision = '2ff2c8b0a045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follower_followed')
    )
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follower_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follower_follower_id'), ['follower_id'], unique=False)

    op.create_table('community_follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='uq_user_community_follow')
    )
    with op.batch_alter_table('community_follower', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_follower_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_follower_user_id'), ['user_id'], unique=False)

    op.drop_table('webhook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('community_follower', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_follower_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_follower_community_id'))

    op.drop_table('community_follower')
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follower_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follower_followed_id'))

    op.drop_table('follower')
    # ### end Alembic commands ###
