"""Add version_doi field to DatasetVersion for Zenodo version tracking

Revision ID: 2ff2c8b0a045
Revises: 46c4bb767ce9
Create Date: 2025-12-08 20:05:40.242025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff2c8b0a045'
down_revision = '46c4bb767ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
=======
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
>>>>>>> 8c4df33 (feat: implement comprehensive versioning system with zenodo sync)
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_doi', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.drop_column('version_doi')

<<<<<<< HEAD
=======
    op.drop_table('comment')
>>>>>>> 8c4df33 (feat: implement comprehensive versioning system with zenodo sync)
    # ### end Alembic commands ###
